config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
	validates_presence_of :task, :due_date
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	def index
		@todos = Todo.all
	end

	def new
		@todo = Todo.new
	end

	def create
		@todo = Todo.new(todo_params)
		if @todo.save
			redirect_to todos_path
		else
			render :new
		end
	end

	def edit
		@todo = Todo.find(params[:id])
	end

	def update
		@todo = Todo.find(params[:id])
		if @todo.update(todo_params)
			redirect_to todos_path
		else
			render :edit
		end
	end

	def destroy
		@todo = Todo.find(params[:id])
		@todo.destroy
		redirect_to todos_path
	end

	private

	def todo_params
		params.require(:todo).permit(:task, :due_date)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_for @todo do |f| %>
	<%= f.label :task, 'Task' %>
	<%= f.text_field :task %>

	<%= f.label :due_date, 'Due date' %>
	<%= f.text_field :due_date %>

	<%= f.submit button %>
<% end %>

<% if @todo.errors.any? %>
 <ul>
   <% @todo.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
 </ul>
<% end %>

app/views/todos/edit.html.erb
<%= render partial:'form', locals: {button: 'Update'} %>

app/views/todos/index.html.erb
<h1>My TODO List</h1>
<table>
	<thead>
		<th>Task</th>
		<th>Due date</th>
		<th>Update?</th>
		<th>Finish?</th>
	</thead>
	<tbody>
		<% @todos.each do |todo| %>
		<tr>
			<td><%= todo.task %></td>
			<td><%= todo.due_date %></td>
			<td><%= link_to 'Update', edit_todo_path(todo) %></td>
			<td><%= link_to 'Finished', todo_path(todo), method: :delete  %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<%= link_to 'New Task', new_todo_path %>

app/views/todos/new.html.erb
<%= render partial: 'form', locals: {button: 'Create'} %>